# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1giedWOYGkMsLfCVG0WRR9UOwX7rpSmI9
"""

import pandas as pd

teacher = pd.DataFrame({
    'FISH': ["Qadamova Zulayho", "I. Azizov", "A.Navrozov", "S. Karimov"],
    "Fani": ["AI", "Sotib olish tamoyillari", "Mikro iqtisodiyot", "AI"],
    "Mashg'ulot turi": ["Amaliy", "Amaliy", "Maruza", "Maruza"],
    "Kafedrasi": ["Axborot Texnologiyalari", "Iqtisod", "Iqtisod","Axborot Texnologiyalari"]
})

print(teacher)

teacher.to_excel('najmiddin.xlsx')